In [1]:
import numpy as np 
a1 = np.random.rand(5) 
print("a1=",a1)
a2 = np.random.rand(5) 
print("a2=",a2)
a3 = np.random.rand(5) 
print("a3=",a3)
a4 = np.random.rand(5) 
print("a4=",a4)
a5 = np.random.rand(5) 
print("a5=",a5)
A = np.array([a1, a2, a3, a4, a5]) 
print("A=",A)
print("The Determinant Of An Random Array:",np.linalg.det(A))
if np.linalg.det(A) ==0.:
    print("The vectors are linearly dependent")
else:
    print("The vectors are linearly independent")

a1= [0.66924471 0.20402516 0.13733326 0.51970681 0.69243519]
a2= [0.27668766 0.84541443 0.13544169 0.19575999 0.9565931 ]
a3= [0.08987573 0.29017479 0.75290548 0.56147143 0.68117025]
a4= [0.85979412 0.86985592 0.75507687 0.7945749  0.03448617]
a5= [0.24270214 0.51089995 0.81698841 0.71547981 0.58488683]
A= [[0.66924471 0.20402516 0.13733326 0.51970681 0.69243519]
 [0.27668766 0.84541443 0.13544169 0.19575999 0.9565931 ]
 [0.08987573 0.29017479 0.75290548 0.56147143 0.68117025]
 [0.85979412 0.86985592 0.75507687 0.7945749  0.03448617]
 [0.24270214 0.51089995 0.81698841 0.71547981 0.58488683]]
The Determinant Of An Random Array: 0.050531305226192584
The vectors are linearly independent


In [17]:
def gram_schmidt(A):    
    Q = np.zeros_like(A)    
    c = np.zeros_like(A[0])   
    
    for i in range(len(A)):        
        c = A[i]        
        for j in range(i):            
            c -= np.dot(Q[j],A[i]) * Q[j]        
        Q[i] = c / np.linalg.norm(c)    
    return Q
Q = gram_schmidt(A)
print("Q=",Q)

Q= [[ 0.59331655  0.68119063  0.00491092  0.23769026  0.35697903]
 [ 0.08231364 -0.21356995  0.9490026   0.14526566  0.1609481 ]
 [-0.62983295  0.49838812  0.16812839 -0.42817944  0.3785696 ]
 [-0.47464382  0.27271557  0.02516163  0.79471792 -0.26101681]
 [ 0.13864932  0.40939309  0.26546126 -0.32785213 -0.79700499]]


In [9]:
import numpy as np
Q = np.array([[1,0,0,0,0],
             [0,1,0,0,0],
             [0,0,1,0,0],
             [0,0,0,1,0],
             [0,0,0,0,1]])
B = Q.T.dot(Q)
print(B)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [3]:
import numpy as np
a1 = np.random.rand(5) 
print("a1=",a1)
a2 = np.random.rand(5) 
print("a2=",a2)
a3 = np.random.rand(5) 
print("a3=",a3)
a4 = np.random.rand(5) 
print("a4=",a4)
a5 = np.random.rand(5) 
print("a5=",a5)
Q = np.array([a1, a2, a3, a4, a5])
print("Q=",Q)
B = Q.T.dot(Q)
print("B=",B)
IIB = np.linalg.inv(B)
print("IIB=",IIB)
print("The Frobeneus Norm=",np.linalg.norm(IIB - 15*np.identity(5), 'fro'))

a1= [0.41832174 0.14131346 0.27772447 0.90832855 0.50727863]
a2= [0.8981211  0.14728843 0.03866329 0.79997227 0.37525502]
a3= [0.5489513  0.49333354 0.30270814 0.58553388 0.67370314]
a4= [0.04314529 0.59153545 0.57156017 0.9128977  0.60466674]
a5= [0.38759024 0.38636652 0.46051527 0.86333727 0.77065919]
Q= [[0.41832174 0.14131346 0.27772447 0.90832855 0.50727863]
 [0.8981211  0.14728843 0.03866329 0.79997227 0.37525502]
 [0.5489513  0.49333354 0.30270814 0.58553388 0.67370314]
 [0.04314529 0.59153545 0.57156017 0.9128977  0.60466674]
 [0.38759024 0.38636652 0.46051527 0.86333727 0.77065919]]
B= [[1.43504983 0.63748729 0.52022588 1.79388348 1.24384885]
 [0.63748729 0.78423464 0.71030273 1.40862519 1.11475511]
 [0.52022588 0.71030273 0.70901329 1.37979646 1.05983146]
 [1.79388348 1.40862519 1.37979646 3.38659978 2.37278297]
 [1.24384885 1.11475511 1.05983146 2.37278297 1.81156132]]
IIB= [[  426.41465026  -256.3283698   1136.87257182  -265.15358431
   -452.8653875 ]
 [ -256.3283698    173